Ssgdha 151 add props ao modal course
sisgha/sisgha-app pull request #33
Opened 2024-04-26 18:21 UTC by Sr-Iury

PULL REQUEST @escuderoDP @guesant revisão de código.

2024-04-26 18:22 UTC, Sr-Iury commented
solicito revisão de código e merge

2024-04-26 18:22 UTC, Sr-Iury commented
@escuderoDP @guesant

2024-04-26 23:03 UTC, guesant requested changes
Vc conseguiu produzir bastante. Esses problemas que vc passou acontecem e faz parte. 90% do tempo é para resolver problema que nem sabemos o que seria KKAKAKAKAKA.

Só preciso que ajuste o fechamento dessa classe que está com uma aspas a mais.

2024-04-27 01:59 UTC, guesant approved these changes

2024-04-27 02:01 UTC, merged